apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-my-bot
  namespace: arcade
subjects:
- kind: ServiceAccount
  name: my-bot
  namespace: arcade
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
